In [5]:
import numpy as np

x = np.array([7,8,9,10],np.int16)

In [6]:
print(x)

[ 7  8  9 10]


In [7]:
print(type(x))

<class 'numpy.ndarray'>


In [8]:
print(x[-2])

9


In [9]:
x = np.array([[1,2.5,3],[5,7,9]],np.int16)
print(x)

[[1 2 3]
 [5 7 9]]


In [10]:
x = np.array([[[1,2,3],[5,7,9]],[[0,10,4],[-8,12,3]]],np.int16)
print(x)

[[[ 1  2  3]
  [ 5  7  9]]

 [[ 0 10  4]
  [-8 12  3]]]


In [11]:
print(x[1,:,1])
print(x[:,0,1])

[10 12]
[ 2 10]


In [12]:
print(x.shape,x.ndim,x.dtype)
print(x.size,x.nbytes)

(2, 2, 3) 3 int16
12 24


In [13]:
print(x.T)
print(x)

[[[ 1  0]
  [ 5 -8]]

 [[ 2 10]
  [ 7 12]]

 [[ 3  4]
  [ 9  3]]]
[[[ 1  2  3]
  [ 5  7  9]]

 [[ 0 10  4]
  [-8 12  3]]]


In [1]:
import numpy as np
print(np.inf)
print(np.NINF)
print(np.NZERO)
print(np.PZERO)
print(np.NAN)

inf
-inf
-0.0
0.0
nan


In [15]:
print(np.e)
print(np.euler_gamma)
print(np.pi)

2.718281828459045
0.5772156649015329
3.141592653589793


In [ ]:
print("hey testing stuffs here")
