In [21]:
import numpy as np
x = np.empty([3,3],np.int8)
print(x)

[[ -32 -100   15]
 [   3    0    0]
 [   0    0    1]]


In [22]:
x = np.eye(4,dtype = np.uint16)
print(x)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [32]:
x = np.eye(4,dtype = np.int16,k=1)
print(x)
x = np.eye(4,dtype = np.int16,k=-1)
print(x)
z = np.identity(5,dtype = np.uint8)
print(z)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [27]:
import numpy as np
x = np.ones((3,3),dtype = np.int16)
print(x)
y = np.zeros((4,4),dtype = np.int8)
print(y)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
z = np.full((2,3),dtype = np.int16,fill_value = np.random.randint(1,100))
print(z)

[[38 38 38]
 [38 38 38]]


In [32]:
T = np.tri(4,4,k=0,dtype = np.int16)
print(T)
print(x)
l = np.triu(x)
print(l)
u = np.tril(x,k = -1)
print(u)

[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [0 1 1]
 [0 0 1]]
[[0 0 0]
 [1 0 0]
 [1 1 0]]
